# escape=`

# The windows version to use, can be any of the tags of https://hub.docker.com/_/microsoft-windows-servercore
# Most used are: ltsc2016, ltsc2019, ltsc2022, 1709, 1803, 1809, 1903, 1909, 2004, 20H2
ARG winversion=1909

FROM mcr.microsoft.com/windows/servercore:$winversion
